version: "3"
services:
  front-end:
    build: frontend
    ports:
      - "8000:8000"
    networks:
      - webnet
  back-end:
    build: backend
    ports:
      - "9000:9000"
    networks:
      - webnet
networks:
  webnet: